<a href="https://colab.research.google.com/github/prog815/coursera-python-for-data-science/blob/master/3_1_coursera_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

ручками проходим примеры
https://www.coursera.org/learn/python-for-data-science/home/week/1

# 3.1 Знакомство с библиотекой NumPy

In [0]:
import numpy as np

In [2]:
x = np.array([1,2,3,4])
x

array([1, 2, 3, 4])

In [3]:
x.dtype

dtype('int64')

In [5]:
x = np.array([1,2,3,4],dtype=np.int16)
print(x)
print(x.dtype)

[1 2 3 4]
int16


In [6]:
x.shape

(4,)

In [7]:
m = np.array([[2,3,4],[5,6,7]])
m

array([[2, 3, 4],
       [5, 6, 7]])

In [9]:
m = np.ones(3)
m

array([1., 1., 1.])

In [12]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [13]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
m = np.random.random((2,4))
m

array([[0.95014254, 0.8241302 , 0.15480953, 0.54253521],
       [0.69239751, 0.83648821, 0.27445599, 0.85628263]])

In [18]:
x[0]

1

In [21]:
m[1,3]

0.8562826333428981

In [22]:
m[:,:2]

array([[0.95014254, 0.8241302 ],
       [0.69239751, 0.83648821]])

In [23]:
m>0.5

array([[ True,  True, False,  True],
       [ True,  True, False,  True]])

In [24]:
m[m>0.5]

array([0.95014254, 0.8241302 , 0.54253521, 0.69239751, 0.83648821,
       0.85628263])

In [25]:
m.flatten()

array([0.95014254, 0.8241302 , 0.15480953, 0.54253521, 0.69239751,
       0.83648821, 0.27445599, 0.85628263])

In [27]:
m.reshape(4,2)

array([[0.95014254, 0.8241302 ],
       [0.15480953, 0.54253521],
       [0.69239751, 0.83648821],
       [0.27445599, 0.85628263]])

In [28]:
m

array([[0.95014254, 0.8241302 , 0.15480953, 0.54253521],
       [0.69239751, 0.83648821, 0.27445599, 0.85628263]])

In [0]:
m.resize(4,2)

In [30]:
m

array([[0.95014254, 0.8241302 ],
       [0.15480953, 0.54253521],
       [0.69239751, 0.83648821],
       [0.27445599, 0.85628263]])

In [0]:
v = np.array([9,10])
w = np.array([11,12])

In [32]:
res = v + w
res

array([20, 22])

In [33]:
np.add(v,w)

array([20, 22])

In [34]:
v - w

array([-2, -2])

In [35]:
v * w

array([ 99, 120])

In [36]:
np.dot(v,w)

219